ALTER TABLE Cidade 
ADD CONSTRAINT Pais_Cidade FOREIGN KEY (PaisID) REFERENCES Pais(PaisID);

ALTER TABLE Cliente
ADD CONSTRAINT Cidade_Cliente FOREIGN KEY (CidadeID) REFERENCES Cidade(CidadeID);

ALTER TABLE Produto
ADD CONSTRAINT Tipo_Produto FOREIGN key (TipoID) REFERENCES Tipo(TipoID);

ALTER TABLE Setor
ADD CONSTRAINT Chefe_Setor FOREIGN KEY (chefe) REFERENCES Funcionario(FuncionarioID) ON UPDATE CASCADE;

ALTER TABLE Pedido
ADD CONSTRAINT Cliente_Pedido FOREIGN KEY (ClienteID) REFERENCES Cliente(ClienteID);
ALTER TABLE Pedido
ADD CONSTRAINT Vendedor_Pedido FOREIGN KEY (Vendedor) REFERENCES Funcionario(FuncionarioID);

ALTER TABLE Itens
ADD CONSTRAINT Produto_Itens FOREIGN KEY (ProdutoID) REFERENCES Produto(ProdutoID) ON UPDATE CASCADE;
ALTER TABLE Itens
ADD CONSTRAINT Pedido_Itens FOREIGN KEY (PedidoID) REFERENCES Pedido(PedidoID) ON UPDATE CASCADE;

ALTER TABLE Funcionario
ADD CONSTRAINT Setor_Funcionario FOREIGN KEY (SetorID) REFERENCES Setor(SetorID) ON UPDATE CASCADE;
ALTER TABLE Funcionario
ADD CONSTRAINT Funcao_Funcionario FOREIGN KEY (FuncaoID) REFERENCES Funcao(FuncaoID) ON UPDATE CASCADE;
ALTER TABLE Funcionario
ADD CONSTRAINT Cidade_Funcionario FOREIGN KEY (CidadeID) REFERENCES Cidade(CidadeID);