-- Problem 1

SELECT WORKDEPT, EMPNO, LASTNAME, SALARY
    FROM EMPLOYEE
        WHERE SALARY >=
		  (SELECT round(AVG(SALARY),2) + 5000
			    FROM EMPLOYEE)
ORDER BY WORKDEPT, EMPNO;


-- Problem 2
SELECT EMPNO,LASTNAME
FROM EMPLOYEE 
WHERE EMPNO NOT IN(SELECT EMPNO FROM EMP_ACT);



-- Problem 3                    
SELECT PROJNO, datediff(PRENDATE,PRSTDATE) AS 'DAYS'
FROM PROJECT
WHERE datediff(PRENDATE,PRSTDATE)=
	(SELECT MIN(datediff(PRENDATE,PRSTDATE))
	 FROM PROJECT);
						

						
-- Problem 4

SELECT D.DEPTNO, D.DEPTNAME, E.LASTNAME, E.FIRSTNME
		FROM DEPARTMENT D inner join EMPLOYEE E
			ON D.DEPTNO = E.WORKDEPT
			WHERE D.DEPTNO NOT IN(SELECT WORKDEPT
				  FROM EMPLOYEE
				  WHERE SEX = 'F');
                  

				  
				  
-- Problem 5
		SELECT LASTNAME, JOB, EDLEVEL,
		DATEDIFF('2000-01-01', HIREDATE)/365 AS 'YEARS',
		SALARY
		FROM EMPLOYEE
		WHERE (JOB, EDLEVEL) IN (SELECT JOB, EDLEVEL
                         FROM EMPLOYEE
                         WHERE LASTNAME = 'STERN')
		ORDER BY SALARY DESC;
