ALTER TABLE Turma
ADD FOREIGN KEY(Cod_Disc) REFERENCES Disciplina(Cod_Disc);
ALTER TABLE Turma
ADD FOREIGN KEY(Cod_Prof) REFERENCES Professores(Cod_Prof);

ALTER TABLE Historico
ADD FOREIGN KEY(TurmaID) REFERENCES Turma(TurmaID);