--ECERCICIO 01
SELECT EMPNO, LASTNAME, BIRTHDATE, SALARY
FROM EMPLOYEE 
WHERE SALARY > 30000 
ORDER BY SALARY DESC;


--EXERCICIO 02
SELECT EMPNO, LASTNAME, FIRSTNME, WORKDEPT
FROM EMPLOYEE
ORDER BY WORKDEPT DESC, LASTNAME DESC; 

--EXERCICIO 03
SELECT DISTINCT(EDLEVEL)
FROM EMPLOYEE 
ORDER BY EDLEVEL DESC;

--EXERCICIO 04
SELECT DISTINCT EMPNO, PROJNO
FROM EMP_ACT
WHERE EMPNO <= 100
ORDER BY EMPNO;

--EXERCICIO 05
SELECT LASTNAME, SALARY, BONUS
FROM EMPLOYEE
WHERE SEX = 'M';

--EXERCICIO 06
SELECT LASTNAME, SALARY, COMM
FROM EMPLOYEE
WHERE SALARY > 20000 AND HIREDATE > '1979-01-01';

--EXERCICIO 07
SELECT LASTNAME, SALARY, BONUS, COMM
FROM EMPLOYEE
WHERE SALARY > 20000 AND BONUS < 400 OR BONUS < 500 AND COMM < 1900
ORDER BY LASTNAME;

--EXERCICIO 08
SELECT LASTNAME, SALARY, BONUS, COMM
FROM EMPLOYEE
WHERE SALARY > 22000 AND BONUS BETWEEN 400 AND 500 AND COMM < 1900
ORDER BY LASTNAME;

--EXERCICIO 09
SELECT PROJNO, ACTNO, EMSTDATE, EMENDATE
FROM EMP_ACT
WHERE PROJNO LIKE 'AD%' AND ACTNO IN (10,80,180)
ORDER BY ACTNO;

--EXERCICIO 10