--ECERCICIO 01
SELECT EMPNO, LASTNAME, BIRTHDATE, SALARY
FROM EMPLOYEE 
WHERE SALARY > 30000 
ORDER BY SALARY DESC;


--EXERCICIO 02
SELECT EMPNO, LASTNAME, FIRSTNME, WORKDEPT
FROM EMPLOYEE
ORDER BY WORKDEPT DESC, LASTNAME DESC; 

--EXERCICIO 03
SELECT DISTINCT(EDLEVEL)
FROM EMPLOYEE 
ORDER BY EDLEVEL DESC;

--EXERCICIO 04
SELECT DISTINCT EMPNO, PROJNO
FROM EMP_ACT
WHERE EMPNO <= 100
ORDER BY EMPNO;

--EXERCICIO 05

